language: node_js
node_js:
  - "node"

sudo: required

services:
  - docker

after_success:
  - docker --version 
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  - docker build -t $IMAGE_NAME .
  - echo "Pushing $IMAGE_NAME:latest"
  - docker tag $IMAGE_NAME:latest "$REMOTE_IMAGE_URL:latest"
  - docker push "$REMOTE_IMAGE_URL:latest"
  - echo "Pushed $IMAGE_NAME:latest"
  - echo "Deploying $TRAVIS_BRANCH on $TASK_DEFINITION"
  - ./bin/ecs-deploy -n $SERVICE -c $CLUSTER -i $REMOTE_IMAGE_URL:latest